export const PRODUCTINFO = {
  CREATETITLE: "Create Product",
  EDITTITLE: "Edit Product",
  NAME: "Product name",
  DESCRIPTION: "Product Description",
  CATEGORY: "Category",
  PRICE: "Price",
  QUANTITY: "In Stock Quantity",
  LINK: "Add Image Link",
  PREVIEW: "image preview!",
  BUTTON: "Upload",
  CREATEBUTTON: "Add Product",
  SAVEBUTTON: "Save Product",
  DROPDOWN: ["Category1", "Category2", "Category3", "Category4", "Catrgory5"],
};
